### ISSUE TITLE
Notebookがシャットダウンされない場合GPUが専有される

### ISSUE THREAD

**Issue by yuziroppe** [KeioAIConsortium/iris#3]
# 背景

JupyterNotebookを起動してプログラムを動かしてプログラムが動き終わった後でさえ、NotebookをshutdownするまでGPUを専有し続けてしまう。

**Comment by 190ikp** [comment]
これirisというよりかはjupyterhubのほうで対処すべき問題な気がする

**Comment by yuziroppe** [comment]
irisをjupyterhub_lxd_spawner側が一方的に利用する方が依存関係的にも良さそうだし、irisはあくまでも状態だけを返すのが良いか。ってことで一旦このissue閉じます。
